### ISSUE TITLE
Delay check for existence of Escenic resources directory

### ISSUE THREAD

**Issue by rfelgent** [oss-ethinking/gradle-escenic-plugin#1]
Hello,

currently the eThinking presentation plugin checks the resource directory for its existence at "plugin apply phase". If the directory does not exist, no corresponding "resources-<PUBLICATION>-<RESOURCE_HOST>" tasks are created.

I have the requirement to generate some files and resource directory on the fly. 

Currently, I configure the plugin like this

```
publication {
    ...
    //Although the resourceBase gets overwritten by a task hook at some later point,
    //You must specify a directory that exists in the moment of the application of plugin 'de.ethinking.escenic.presentation' !
    //A non existent directory prevents the plugin from creation of the corresponding resource upload tasks :-(
    resourcesBase = project.file('src/escenic_resources')    
    ...
}
```

and overwrite/set the resourceBase for each specific upload task.

```
project.tasks.whenTaskAdded { task ->
        if (task.getName() != null && task.getName().startsWith("resources-")) {
              task.dependsOn classes

             //ensure the correct base dir of the resources to upload depending on stage
            task.doFirst {
                println("Executing resource upload task '" + task.getName() + "'")
                //task name like resources-news38-dev1
               def stage = task.getName().split("-")[2]
               def resourcesBase = project.file("build/tmp/escenic_resoures/" + stage + "/")
               if (!resourcesBase.exists()) {
                  throw new IllegalStateException("The Escenic resource directory '" + resourcesBase + "' does not exist. Was task ':configuration:processResources' correctly performed?")
               }
               task.resourcesBase = resourcesBase
          }
     }
}
```

Ideally, I want the plugin to do its check at some later time! Ideally at the moment before the upload begins. If the directory does not exist the plugin should throw an exception.

**Comment by simijhag** [comment]
Your task can choose a task dependency now for preprocessing of resources files. The latest release provide the preparePublicationResources task which could depends on your task. All resources upload tasks depends on the preparePublicationResources task.
