### ISSUE TITLE
stage dependent resourcesDir

### ISSUE THREAD

**Issue by rfelgent** [oss-ethinking/gradle-escenic-plugin#2]
Hello,

currently the plugin provides to specify different Escenic-admin URLs by using "resourceHost" tag.

I would like to have a feature allowing the definition of stage (resourceHost) dependent "resourcesDir".

**Comment by simijhag** [comment]
We provide an advanced resourcesHost  definition which allows you to define a resourceBase for any specific  resourcesHosts. Check out release the latest release.
