### ISSUE TITLE
Adapt the dependency resolution to "maven.escenic.com"

### ISSUE THREAD

**Issue by rfelgent** [oss-ethinking/gradle-escenic-plugin#3]
Hello,

the plugin works nicely with the old (deactivated) repository layout of "technet.escenic.com", e.g.:
http://technet.escenic.com/downloads/release/57/

Switching to "maven.escenic.com" breaks the build, as no dependencies can be found.

**Comment by simijhag** [comment]
You can use the maven repository directly with credentials.
repositories {
    maven {
        credentials {
            username 'user'
            password 'password'
        }
        url "http://repo.mycompany.com/maven2"
    }
}
The provided escenicRepository() of the plugin is only a shortcut for creating a ivy repository.

**Comment by simijhag** [comment]
We provide now a shortcut for the escenic maven repository
