### ISSUE TITLE
Making tasks "resources-XXX-XXX" available for external process

### ISSUE THREAD

**Issue by rfelgent** [oss-ethinking/gradle-escenic-plugin#4]
Hello,

currently you define the Escenic resource upload tasks (aka resources-XXX-XXX) via a static configuration like

```
publication {

   publications "pub1","pub2","pub3"
   resourcesHost "dev","http://149.221.XXX.XXX:8080/escenic-admin/publication-resources/"
   resourcesHost "uat","http://149.221.XXX.XXX:8080/escenic-admin/publication-resources/"
   ignoreResourcesFailure = false
   resourcesBase = project.file('build/resources/main/META-INF/resources')
}
```
The plugin creates the resources-XXX-XXX tasks on the fly based on the "publication" configuration. 

I have the requirement to make *all* resources tasks available for an external process. Ideally a comma separated list of task names grouped/filtered by the resourceHost. The output of it should be on stdout or a file.

My current workaround is to use 

`./gradlew tasks | grep -i resources | grep -i ${resourceHost}`

In my opinion the plugin should offer this functionality.

**Comment by simijhag** [comment]
New collection tasks are added for a apply any resources to a specific host 

resourcesHost-{host key like dev or production}
